# Generated by Django 3.2.8 on 2021-10-17 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Location', models.CharField(max_length=200)),
                ('Image', models.ImageField(upload_to='picture')),
                ('Description', models.TextField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Visibility', models.CharField(max_length=200)),
                ('Category', models.CharField(max_length=200)),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment', models.TextField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Replyid', models.IntegerField(default=0)),
                ('Likes', models.IntegerField(default=0)),
                ('By', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Photoid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PhotoApp.photo')),
            ],
        ),
    ]
